---
schedules:
- cron: "0 19 * * *"
  displayName: Nightly Builds
  branches:
    include:
    - master
  always: true

trigger: none

pool:
  vmImage: 'ubuntu-20.04'

stages:

# Fedora

- stage: fedora_latest_Ansible_Core_2_15
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: true

- stage: fedora_latest_Ansible_Core_2_16
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: ""
      skip_git_test: true

- stage: fedora_latest_Ansible_Core_2_17
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.17"
      skip_git_test: true

# Galaxy on Fedora

- stage: Galaxy_fedora_latest_Ansible_Core_2_17
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.17,<2.18"
      skip_git_test: true
      test_galaxy: true

# Fedora Rawhide

- stage: fedora_rawhide_Ansible_Core_2_17
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-rawhide
      ansible_version: "-core >=2.17,<2.18"
      skip_git_test: true

# CentoOS 9 Stream

- stage: c9s_Ansible_Core_2_15
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c9s
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: true

- stage: c9s_Ansible_Core_2_16
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c9s
      ansible_version: "-core >=2.16,<2.17"
      skip_git_test: true

- stage: c9s_Ansible_Core_2_17
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c9s
      ansible_version: "-core >=2.17,<2.18"
      skip_git_test: true

# CentOS 8 Stream only works up to ansible-core 2.16.z

- stage: c8s_Ansible_Core_2_15
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c8s
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: true

- stage: c8s_Ansible_Core_2_16
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c8s
      ansible_version: "-core >=2.16,<2.17"
      skip_git_test: true
