---
schedules:
- cron: "0 19 * * *"
  displayName: Nightly Builds
  branches:
    include:
    - master
  always: true

trigger: none

pool:
  vmImage: 'ubuntu-20.04'

stages:

# Fedora

- stage: FedoraLatest_Ansible_Core_2_13
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.13,<2.14"
      skip_git_test: false

- stage: FedoraLatest_Ansible_Core_2_14
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.14,<2.15"
      skip_git_test: false

- stage: FedoraLatest_Ansible_Core_2_15
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: true

- stage: FedoraLatest_Ansible_latest
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: ""
      skip_git_test: true

# Galaxy on Fedora

- stage: Galaxy_FedoraLatest_Ansible_Core_2_13
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.13,<2.14"
      skip_git_test: false
      test_galaxy: true

- stage: Galaxy_FedoraLatest_Ansible_Core_2_14
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.14,<2.15"
      skip_git_test: false
      test_galaxy: true

- stage: Galaxy_FedoraLatest_Ansible_Core_2_15
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: true
      test_galaxy: true

# Fedora Rawhide

- stage: FedoraRawhide_Ansible_Core_2_13
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-rawhide
      ansible_version: "-core >=2.13,<2.14"
      skip_git_test: false

- stage: FedoraRawhide_Ansible_Core_2_14
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-rawhide
      ansible_version: "-core >=2.14,<2.15"
      skip_git_test: false

- stage: FedoraRawhide_Ansible_Core_2_15
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-rawhide
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: true

- stage: FedoraRawhide_Ansible_latest
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-rawhide
      ansible_version: ""
      skip_git_test: true

# CentoOS 9 Stream

- stage: c9s_Ansible_Core_2_13
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c9s
      ansible_version: "-core >=2.13,<2.14"
      skip_git_test: false

- stage: c9s_Ansible_Core_2_14
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c9s
      ansible_version: "-core >=2.14,<2.15"
      skip_git_test: false

- stage: c9s_Ansible_Core_2_15
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c9s
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: true

- stage: c9s_Ansible_latest
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c9s
      ansible_version: ""
      skip_git_test: true

# CentOS 8 Stream

- stage: c8s_Ansible_Core_2_13
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c8s
      ansible_version: "-core >=2.13,<2.14"
      skip_git_test: true

- stage: c8s_Ansible_Core_2_14
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c8s
      ansible_version: "-core >=2.14,<2.15"
      skip_git_test: false

- stage: c8s_Ansible_Core_2_15
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c8s
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: true
