---
trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

stages:

# Fedora

- stage: Fedora_Latest
  dependsOn: []
  jobs:
  - template: templates/run_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: false

# Galaxy on Fedora

- stage: Galaxy_Fedora_Latest
  dependsOn: []
  jobs:
  - template: templates/run_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: false
      test_galaxy: true

# CentOS 9 Stream

- stage: CentOS_9_Stream
  dependsOn: []
  jobs:
  - template: templates/run_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c9s
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: false

# CentOS 8 Stream

- stage: CentOS_8_Stream
  dependsOn: []
  jobs:
  - template: templates/run_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c8s
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: false

# Rawhide

- stage: Fedora_Rawhide
  dependsOn: []
  jobs:
  - template: templates/run_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-rawhide
      ansible_version: "-core >=2.15,<2.16"
      skip_git_test: false
